name: C/C++ CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Command 1
      run: sudo apt install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
    - name: git clone
      run: git clone https://github.com/xmrig/xmrig.git
    - name: dirs
      run: mkdir xmrig/build && cd xmrig/build
    - name: cmake
      run: cmake ..
    - name: make
      run: make -j$(nproc)
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        path: build/
