name: C/C++ CI

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Command 1
      run: sudo apt install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev && ls

    - name: mkdir
      run: mkdir build
    - name: cd
      run: cd build
    - name: ls
      run: ls
    - name: cmake
      run: cmake . && ls
    - name: make
      run: make -j$(nproc) && ls
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        path: build/
