name: Build

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: depend
      run: sudo apt install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev && ls
    - name: mkdir
      run: mkdir build
    - name: cd
      run: cd build
    - name: cmake
      run: cmake .
    - name: make
      run: make -j$(nproc)
    - name: cd
      run: cd ..
    - name: ls
      run: ls
    - name: cd
      run: cd ..
    - name: ls
      run: ls
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.4.3
      with:
          path: ~/xmrig/xmrig
